# 工作流名称
name: WJKC Daily Check-in

on:
  # 触发条件
  # 1. 定时触发：每天的 UTC 时间 18:00 (北京时间凌晨 2:00) 运行
  #    您可以访问 https://crontab.guru/ 来生成自己的时间
  schedule:
    - cron: '0 18 * * *'
  
  # 2. 手动触发：允许你在 Actions 页面手动运行此工作流进行测试
  workflow_dispatch:

# 任务定义
jobs:
  checkin:
    # 运行环境：使用最新的 Ubuntu 虚拟机
    runs-on: ubuntu-latest
    
    # 任务步骤
    steps:
      # 步骤一：检出你的代码
      # 这是为了让虚拟机可以访问到仓库中的 index.js 文件
      - name: Checkout repository
        uses: actions/checkout@v4

      # 步骤二：设置 Node.js 环境
      # 这是为了提供运行 index.js 所需的 JavaScript 运行时
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20' # 使用一个稳定且较新的 Node.js 版本

      # 步骤三：运行签到脚本
      # - `run: node index.js` 是核心命令
      # - `env:` 部分将 GitHub Secrets 注入到脚本的环境变量中，确保安全
      - name: Run WJKC Check-in Script
        run: node index.js
        env:
          WJKC_TOKEN: ${{ secrets.WJKC_TOKEN }}
          NOTIFY: ${{ secrets.NOTIFY }}
